# Generated by Django 3.2.9 on 2021-12-01 21:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand', models.CharField(max_length=50)),
                ('model', models.CharField(max_length=70)),
            ],
        ),
        migrations.CreateModel(
            name='Engine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('engine_capacity', models.PositiveSmallIntegerField()),
                ('fuel_type', models.TextField(choices=[('Petrol', 'Petrol'), ('Diesel', 'Diesel'), ('LPG', 'Lpg'), ('Hybrid', 'Hybrid'), ('Electric', 'Electric'), ('Etanol', 'Etanol'), ('Hydrogen', 'Hydrogen')])),
                ('cylinders', models.PositiveSmallIntegerField()),
                ('power', models.PositiveSmallIntegerField()),
                ('torque', models.PositiveSmallIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Transmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transmission_system', models.CharField(choices=[('Manual', 'Manual'), ('Automatic', 'Automatic')], max_length=50)),
                ('number_of_gears', models.PositiveSmallIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Generation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('generation', models.CharField(max_length=50)),
                ('car_model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cars.car')),
            ],
        ),
        migrations.CreateModel(
            name='CarStats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('height', models.PositiveSmallIntegerField(blank=True, help_text='Car height in cm', null=True)),
                ('width', models.PositiveSmallIntegerField(blank=True, help_text='Car width in cm', null=True)),
                ('length', models.PositiveSmallIntegerField(blank=True, help_text='Car length in cm', null=True)),
                ('num_of_seats', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('max_boot_capacity', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('min_boot_capacity', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('num_of_doors', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('turning_radius', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('year_of_start_production', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('year_of_end_production', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('fuel_tank_capacity', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('weight', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('v_max', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('acceleration_0_100', models.FloatField(blank=True, null=True)),
                ('acceleration_100_200', models.FloatField(blank=True, null=True)),
                ('time400', models.FloatField(blank=True, help_text='Time of 400 meters drag race', null=True)),
                ('nurburgring_lap_time', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('engine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cars.engine')),
                ('transmission', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='cars.transmission')),
            ],
        ),
        migrations.CreateModel(
            name='BodyType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('body_type', models.CharField(choices=[('Sedan', 'Sedan'), ('Wagon', 'Wagon'), ('Coupe', 'Coupe'), ('Hatchback', 'Hatchback'), ('SUV', 'Suv'), ('Convertible', 'Convertible'), ('Pickup', 'Pickup'), ('Minivan', 'Minivan'), ('Van', 'Van')], max_length=50)),
                ('generations', models.ManyToManyField(to='cars.Generation')),
            ],
        ),
    ]
